Traceback (most recent call last):
  File "1.py", line 29, in <module>
    raise Exception('This is error message...')
Exception: This is error message...
Traceback (most recent call last):
  File "1.py", line 29, in <module>
    raise Exception('This is error message...')
Exception: This is error message...
